name: Maven GitHub Actions Sample

on: [workflow_dispatch]

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21 ]
    name: Java ${{ matrix.java }} compile
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-package: jdk
          java-version: ${{ matrix.java }}

      - name: Compile the Project
        run: ./mvnw -f github-actions-java-maven/pom.xml -B compile

  build:
    runs-on: ubuntu-latest
    needs: compile
    name: Build the Maven Project
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
          java-package: jdk
          cache: 'maven'

      - name: Build and test project
        run: ./mvnw -f github-actions-java-maven/pom.xml -B verify

      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact.jar
          path: github-actions-java-maven/target/github-actions-java-maven.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Build Docker Container and Deploy to Kubernetes
    steps:
      - uses: actions/checkout@v3

      - name: Download Maven build artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact.jar
          path: github-actions-java-maven/target

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}

      - name: Build Docker container
        working-directory: github-actions-java-maven
        run: |
          docker build -t ghcr.io/naman1027/sampletest:latest .

      - name: Push Docker images
        run: |
          echo "Pushing Docker image to Container Registry (e.g. ECR)"
          docker push ghcr.io/naman1027/sampletest:latest
